version: "3.7"

services:
  postgres:
    image: postgres:14.1
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    ports:
      - "5432:5432"
    container_name: notifier-db
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_LIST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}


volumes:
  postgres_data:
    driver: local


networks:
  local:
    driver: bridge
